### ISSUE TITLE
Moscow - неправильное время пересадок

### ISSUE THREAD

**Issue by asdzxcasd** [Utyff/pMetro-maps#6]
* ЦСКА - физически одна станция, так что время пересадки должно быть 0. То же самое и для остальных станций от Делового центра до Петровского парка

* Хорошёво - Хорошёвская - там время пересадки точно больше двух минут, потому что нужно пройти большое расстояние по поверхности

* Измайлово - Партизанская - в официальной схеме есть обозначение "3 мин". Это время, которое нужно было пройти по улице до того, как построили навес между выходами. Реальное время пересадки порядка 7-9 минут.

* Уже довольно давно есть пересадка с Нагатинской на Верхние котлы, хотя тоже довольно долгая.

**Comment by Utyff** [comment]
Я написал вопрос Борису - как лучше присылать изменения.

**Comment by Utyff** [comment]
> есть пересадка с Нагатинской на Верхние котлы,
> хотя тоже довольно долгая.

На официальной схеме этой пересадки нет. Судя по яндексу, там идти 1км - 12мин.
Этой пересадкой кто-нибудь пользуется? Есть смысл добавлять ее?

**Comment by asdzxcasd** [comment]
На новых схемах пересадка есть, рядом написано время 11 мин. От платформы до платформы идти 1.1км, то есть около 13 минут. Думаю, что есть смысл её добавить, потому что через эту пересадку можно добраться быстрее, если нужно попасть с юга серой ветки на одну из станций МЦК. В противном случае приходится делать много пересадок.

**Comment by asdzxcasd** [comment]
Обнаружил ещё несколько недочётов. Постараюсь в ближайшее время всё исправить и выложить сюда.
* Перекрываются названия станции "Парк Победы"
* Перекрывается номер ветки 8 и название станции "Новокосино"
* Перекрываются ссылки на схемы электричек и название станции "Медведково"
* БКЛ, Бутовская линия, Монорельс, МЦК теперь нумеруются с 11 по 14
* В файле Metro.vec ссылка на файл 1.png, который отсутствует в pmz

**Comment by Utyff** [comment]
Борис вникает в каждую мелочь когда принимает обновления.
Чтобы пройти его контроль и заслужить доверие :) лучше сначала делать важные изменения и хорошо их прокоментировать.
Если сделать много изменений сразу Борис может и не принять их, не хватит терпения вникнуть во все..
И еще. Этот репозиторий я закрыть хочу. Делай комиты в github.com/pMetro/pMetro-maps.git

**Comment by asdzxcasd** [comment]
Ясно, буду выкладывать туда

**Comment by dimqua** [comment]
>пройти его контроль и заслужить доверие

Почему бы не форкнуть, имеющиеся карты? Лицензия это позволяет.

**Comment by Utyff** [comment]
Нужно будет постоянно мерджить изменения новой ветки и того что Борис делает.
Дмитрий, вы займетесь?

**Comment by dimqua** [comment]
Я не знаю, стоит ли оно того, поэтому и спросил. :-)

**Comment by Utyff** [comment]
Больше 1000 пользователей андроид версии будут пользоваться результатом Вашей работы.
Оно стоит.
Займетесь?

**Comment by dimqua** [comment]
Попробую, но пока мерджить нечего? Нужна новая ветка?
https://github.com/pMetro/pMetro-maps/pull/4

**Comment by Utyff** [comment]
Сейчас мерджить нечего.
Ветка сделана, называется - for_Boris.
В нее можно вносить новые изменения и мерджить в нее изменения которые делает Борис, из ветки Master. Я их туда вношу.
